### ISSUE TITLE
Redirect loop on some repos.

### ISSUE THREAD

**Issue by dmitshur** [gophergala/appstract#1]
I am guessing it's likely due to the capital letter in the path.

http://go-appstract.appspot.com/view/shurcooL/sanitized_anchor_name results in a redirect loop.

```
curl -i -L http://go-appstract.appspot.com/view/shurcooL/sanitized_anchor_name
HTTP/1.1 302 Found
Location: /view/shurcooL/sanitized_anchor_name
Content-Type: text/html; charset=utf-8
Date: Thu, 29 Jan 2015 20:47:38 GMT
Server: Google Frontend
Content-Length: 59
Alternate-Protocol: 80:quic,p=0.02

HTTP/1.1 302 Found
Location: /view/shurcooL/sanitized_anchor_name
Content-Type: text/html; charset=utf-8
Date: Thu, 29 Jan 2015 20:47:38 GMT
Server: Google Frontend
Content-Length: 59
Alternate-Protocol: 80:quic,p=0.02

HTTP/1.1 302 Found
Location: /view/shurcooL/sanitized_anchor_name
Content-Type: text/html; charset=utf-8
Date: Thu, 29 Jan 2015 20:47:39 GMT
Server: Google Frontend
Content-Length: 59
Alternate-Protocol: 80:quic,p=0.02

HTTP/1.1 302 Found
Location: /view/shurcooL/sanitized_anchor_name
Content-Type: text/html; charset=utf-8
Date: Thu, 29 Jan 2015 20:47:39 GMT
Server: Google Frontend
Content-Length: 59
Alternate-Protocol: 80:quic,p=0.02

HTTP/1.1 302 Found
Location: /view/shurcooL/sanitized_anchor_name
Content-Type: text/html; charset=utf-8
Date: Thu, 29 Jan 2015 20:47:40 GMT
Server: Google Frontend
Content-Length: 59
Alternate-Protocol: 80:quic,p=0.02

^C
~ $ 
```

**Comment by CorgiMan** [comment]
Hmm weird. I think the program cannot find the structure in your program
because it is to small.
I think it doesn't recognize the function calls unicode.IsLetter(r) ||
unicode.IsNumber(r) because they are in a switch statement. It should
recognize them though...

I think the program cannot handle empty repos because it doesn't know what
to put in the database... This project is currently being judged for the
gophergala so I'm not allowed to make changes. Maybe I'll fix it after a
week or so.

In the meanwhile: try adding some functions to your main package. This
might help!
Good luck

2015-01-29 21:48 GMT+01:00 Dmitri Shuralyov notifications@github.com:

**Comment by dmitshur** [comment]
This appears to be working now, so closing issue. Thank you for fixing it!

**Comment by CorgiMan** [comment]
Interesting because I didn't change a thing! Have fun with it ;)
